/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.google.gson.JsonArray;

import java.io.IOException;

public class App {
    public static void main(String[] args) throws IOException, InterruptedException {
        Server server = new Server();
        System.out.println("server will run on localhost, port " + server.getPort());
        server.start();
    }
}